apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: obsidian-ai
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 5
      containers:
        image: gcr.io/obsidian-ai/obsidian-ai:0.0.1
        ports:
          - containerPort: 8080
            name: http1
        resources:
          limits:
            cpu: "4"
            memory: 8192Mi
        env:
        - name: STABILITY_KEY
          valueFrom:
            secretKeyRef:
              key: 1
              name: obsidian-ai
      timeoutSeconds: 1200
