apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: obsidian-ai
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 5
      serviceAccountName: obsidian-ai-cloud-run@obsidian-ai.iam.gserviceaccount.com
      containers:
        image: gcr.io/obsidian-ai/obsidian-ai:0.0.2
        ports:
          - containerPort: 8080
            name: http1
        resources:
          limits:
            cpu: "4"
            memory: 8192Mi
        volumeMounts:
          - name: settings
            readOnly: true
            mountPath: /app
      volumes:
        - name: settings
          secret:
            secretName: OBSIDIAN_AI
            items:
              - key: "2"
                path: .env
      timeoutSeconds: 1200
